### ISSUE TITLE
Amélioration de la distinction des sollicitations venant de notre API

### ISSUE THREAD

**Issue by LucienMLD** [betagouv/conseillers-entreprises#3493]
```[tasklist]
### Tasks
- [x] Stats : filtre pour distinguer les utilisateurs d'API
- [x] Mail confirmation de votre demande : afficher le site d'origin, comme pour les iframes
- [x] Tester le retour des mails mauvaises qualité provenant de l'api
```
