### ISSUE TITLE
Satisfaction responsables

### ISSUE THREAD

**Issue by clairezed** [betagouv/conseillers-entreprises#3501]
Satisfaction (suite) : donner une vue agrégée des retours des entreprises aux responsables selon leur périmètre local, régional, national. Possibilité de les mettre en "lu" en masse ?
```[tasklist]
### Tasks
- [x] MaJ company_satisfaction.share
- [x] Migration pour créer satisfactions pour les responsables
- [x] share_satisfaction en asynchrone
- [x] Filtre par antenne pour responsable
- [x] Batch "marquer comme vu"
- [x] Check methode patch / post
- [x] Essayer nouveauté turbo sur le scroll
- [x] Ordonnancement des onglets
- [x] MaJ du compteur "Seen
- [x] Suppression des checkbox pour l'onglet "seen"
- [x] Vérif avec simple utilisateur
- [x] Réparer l'affichage des filtres
- [x] Vérif "Tout marquer comme vu"
- [x] Fix erreur js quand pas de batch_check_button
```
