### ISSUE TITLE
ONGLET VEILLE - APPROFONDIR LE SUIVI QUALITÉ 2 

### ISSUE THREAD

**Issue by clairezed** [betagouv/conseillers-entreprises#3526]
APPROFONDIR LE SUIVI QUALITÉ 2 
- suivi des MER refusées avec commentaires (Carte : besoin standard + afficher antenne qui a refusé et son commentaire)
- suivi des MER non clôturées avec stock important (Carte : expert "Panier Qualité" sans "risque d'abandon")

Dans une visée pédagogique, faire remonter les conseillers/équipes ayant plus de 7 besoins en cours dont la date de prise en charge pour la MER est supérieure à 1 mois. 
- A partir de maintenant pour la date de départ (plus d’un mois)
- Objectif : appeler pour pédagogie quand on a le temps en ciblant nos gros producteurs de vieux « en cours ».
- Vérifier les proportions que cela représente par région avec Lucien et Claire : combien cela représente d'équipes par région avec ces deux critères ? 

Pour que le produit continue de refléter les priorités de l'équipe, voici un redécoupage proposé : 
	
1/ Sollicitations - ok

2/ Risques d'échec - ok

3/ Paniers qualité - ok 

4/ Suivi qualité - nouveau nom !
- MER en attente - ok 
- Commentaires des MER refusées - nouveau ! 

5/ Veille - pousser en dernier sur la droite
- Besoins en suivis - ok 
- Équipe avec stock en cours - nouveau !
---

```[tasklist]
### Tasks
- [ ] Récupérer la liste des besoins avec commentaire de MER refusé
- [ ] Carte besoin avec commentaire refusé
- [x] Récupérer la liste des experts avec stock
- [x] Carte experts avec stock
```
