### ISSUE TITLE
Chantier coopération - modèle de données / gestion en admin

### ISSUE THREAD

**Issue by clairezed** [betagouv/conseillers-entreprises#3700]
- possibilité de visualiser la liste des coopérations en admin avec le ou les iframes associées
- pouvoir associer un logo à une coopération différent de l'institution ? réutiliser pour les sollicitations + le mail de confirmation à l'entreprise
- graphiques stats acquisition liés aux coopérations 
---
### TODO
- [x] Clean des champs dans landings : `display_pde_partnership_mention`,  `display_partner_url`,  `institution_id`
- [x] Faire de toutes les iframes des coop (archivées si besoin)
- [x] Archiver / désarchiver une cooperation (archivage auto de toutes les landings liées)
- [x] Affichages logos dans 1er email entreprise (+ url cooperation)
- [x] Transformer `partner_url` : queue de l'url
- [x] Optimiser logos
- [x] Remove `theme.cooperation`
- [x] Affichage logo dans vignettes solicitation
- [x] Traductions
- [x] Test enregistrement de la coop d'une sollicitation
- [x] sur mail relance : mentionner aussi Coopération
- [ ] idem sur mauvaise qualité (tous les mails auto)

---
