### ISSUE TITLE
Afficher les territoires et zones d’interventions sur une carte

### ISSUE THREAD

**Issue by n-b** [betagouv/conseillers-entreprises#625]
```[tasklist]
### 1. Géographie dans la base
- [x] Intégration des contours géos des communes et des régions à partir du COG géolocalisé (avec des index par code geo) #3007
- [x] Script de téléchargement et de mise à jour en base, documentaton #3007
- [x] Création des contours des antennes par `ST_Union` des communes. #3008
- [x] Performance: vue matérialisée ou colonne spécifique en base, création initiale en batch, et mise à jour quand `antennes.communes` est modifié. #3008
```
```[tasklist]
### 2. Statistiques par zone géographique
- [ ] Calcul du nombre d’agents
- [ ] Calcul du nombre de besoins clôturés (par état)
- [ ] Scope par Institution et par thématique
- [ ] Granularité par Antenne ou par Région
- [ ] Performance: vues matérialisées des statistiques par `antenne_id` et par `territory_id`; création en batch et mise à jour manuelle.
```
```[tasklist]
### 3. Cartes!
- [ ] Intégration de d3-geo.js (et bertin.js?)
- [ ] Affichage (en annuaire) des zones des antennes d’une institution
- [ ] Affichage des stats par zone géographique, avec un contrôle du scope
```
